spring.application.name=swissdentalline
spring.data.mongodb.uri=${MONGODB_URI} 
spring.data.mongodb.database=swissdentalline
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${AUTH0_DOMAIN}/
