spring.application.name=swissdentalline
spring.data.mongodb.uri=${MONGODB_URI} 
spring.data.mongodb.database=swissdentalline
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${AUTH0_DOMAIN}/

# Spring AI OpenAI Configuration
spring.ai.openai.api-key=${OPENAI_API_KEY}
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
